name: Submit Pull Request to master
on:
  push:
    branches:
    - "develop"
  # create:

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: pull-request
      id: pr_master
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "master"                      # If blank, default: master
        pr_title: "Pulling ${{ steps.extract_branch.outputs.branch }} into master" # Title of pull request
        pr_allow_empty: true                              # Creates pull request even if there are no changes
        github_token: ${{ secrets.GITHUB_TOKEN }}
        pr_label: "master"
